apiVersion: apps/v1
kind: Deployment
metadata:
  name: digidine-deployment
  labels:
    app: digidine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: digidine
  template:
    metadata:
      labels:
        app: digidine
    spec:
      containers:
      - name: digidine-container
        image: digidine:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
            memory: "200Mi"
          limits:
            cpu: "600m"
            memory: "500Mi"
