version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "admin"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    networks:
      - backend
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "admin"
      ME_CONFIG_MONGODB_URL: "mongodb://root:admin@mongo:27017/"
      ME_CONFIG_BASICAUTH: "false"

  app:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./src/main/resources/application-docker.env
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - backend
    command:  "./wait-for-it.sh mongo 27017 --java -jar app.jar"

# Define named volumes
volumes:
  mongodb_data:
    driver: local

networks:
  backend:
