version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: DigiDine
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./src/main/resources/application-docker.env
    ports:
      - "8080:8080"
    networks:
      - backend

volumes:
  db_data:

networks:
  backend: