apiVersion: v1
kind: Service
metadata:
  name: mongo  # Nome do serviço ajustado para 'mongo'
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017  # Porta externa
      targetPort: 27017  # Porta do container
  type: LoadBalancer