apiVersion: v1
kind: Service
metadata:
  name: digidine-service
  labels:
    app: digidine
spec:
  selector:
    app: digidine
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP