spring:
  application:
    name: digidine

  data:
    mongodb:
      host: mongo
      port: 27017
      authentication-database: admin
      username: root
      password: admin  # Ensure the password is included
      database: digidine_db

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

aws:
  lambda:
    url: https://your-api-gateway-url/your-lambda-function
